### ISSUE TITLE
Add failOnWarning option

### ISSUE THREAD

**Issue by ironsidevsquincy** [pkuczynski/csslint-maven-plugin#1]
Currently the build does not fail if cssLint warnings are thrown.

Can a 'failOnWarning' option be added

**Comment by tomasz-oponowicz** [comment]
In 0.8.1 version, we've introduced "errors" and "warnings" options. You can define all rules in "errors" options and it will cause build failure. It's not perfect but good enough. We have to think about "failOnWarning" option, because there isn't easy way to get information about warnings from csslint tool.

**Comment by pkuczynski** [comment]
I think spliting <rules/>" into <errors/> and <warnings/> allows to achieve what Darren wants, so I am closing this issue.

**Comment by ironsidevsquincy** [comment]
It does indeed. Thanks
